# https://alacritty.org/config-alacritty.html

[env]
TERM = "xterm-256color"

[font]
size = 18
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family ="JetBrainsMono Nerd Font", style = "Italic" }

[font.offset]
x = 0
y = 2

[window]
decorations = "Full"	# Full/ None
dimensions = { columns = 96, lines = 24 }
padding.x = 4
padding.y = 2
#opacity = 0.9
option_as_alt = "None" # macOS option key

[keyboard]
bindings = [
	# MacOS compatibility binds
	{ key = "Key0", mods = "Command", chars = "\u001B0" },
	{ key = "Key1", mods = "Command", chars = "\u001B1" },
	{ key = "Key2", mods = "Command", chars = "\u001B2" },
	{ key = "Key3", mods = "Command", chars = "\u001B3" },
	{ key = "Key4", mods = "Command", chars = "\u001B4" },
	{ key = "Key5", mods = "Command", chars = "\u001B5" },
	{ key = "Key6", mods = "Command", chars = "\u001B6" },
	{ key = "Key7", mods = "Command", chars = "\u001B7" },
	{ key = "Key8", mods = "Command", chars = "\u001B8" },
	{ key = "Key9", mods = "Command", chars = "\u001B9" },

	{ key = "Left",  mods = "Command", chars = "\u001B[1;9D" },
	{ key = "Right", mods = "Command", chars = "\u001B[1;9C" },
	{ key = "Up",    mods = "Command", chars = "\u001B[1;9A" },
	{ key = "Down",  mods = "Command", chars = "\u001B[1;9B" },

	#{ key = "H", mods = "Command", chars = "\u001Bh" },		# cmd+h needs to be unbound from hiding the active window in the MacOS system settings
	#{ key = "J", mods = "Command", chars = "\u001Bj" },
	#{ key = "K", mods = "Command", chars = "\u001Bk" },
	#{ key = "L", mods = "Command", chars = "\u001Bl" },
	{ key = "R", mods = "Command", chars = "\u001Br" },
	{ key = "T", mods = "Command", action = "None" },
	#{ key = "T", mods = "Command", chars = "\u001Bt" },
	#{ key = "W", mods = "Command", chars = "\u001Bw"},

	{ key = "Left",  mods = "Command|Shift", chars = "\u001B[1;4D" },
	{ key = "Right", mods = "Command|Shift", chars = "\u001B[1;4C" },
	{ key = "Up",    mods = "Command|Shift", chars = "\u001B[1;4A" },
	{ key = "Down",  mods = "Command|Shift", chars = "\u001B[1;4B" },
]

[scrolling]
history = 10000
multiplier = 1

[selection]
#save_to_clipboard = true

## Catppuccin Macchiato 
[colors.primary]
background = '0x24273a'
foreground = '0xcad3f5'

[colors.cursor]
text = '0x24273a'
cursor = '0xf4dbd6'

[colors.normal]
black   = "0x1e2030"
red     = "0xed8796"
green   = "0xa6da95"
yellow  = "0xeed49f"
blue    = "0x8aadf4"
magenta = "0xc6a0f6"
cyan    = "0x91d7e3"
white   = "0xb8c0e0"

[colors.bright]
black   = "0x363a4f"
red     = "0xf0a4b3"
green   = "0xb8e0ac"
yellow  = "0xf5e0bb"
blue    = "0xa5c9ff"
magenta = "0xd6b4ff"
cyan    = "0xa5dff9"
white   = "0xcad3f5"
